/* eslint-disable */
/* global WebImporter */

/**
 * Parser for cards-doormat variant.
 * Base block: cards
 * Source: https://www.cbsa-asfc.gc.ca/menu-eng.html
 * Selector: section.col-md-8 .wb-eqht .gc-drmt
 *
 * Source structure: Each section.gc-drmt contains:
 *   - h3.h5 > a[href] (heading link)
 *   - p (description text)
 *
 * Target: Cards block (no images) with 1 column per row.
 *   Row 0 = block name (auto-generated by createBlock)
 *   Each subsequent row = one card cell containing heading link + description
 *
 * The selector matches individual .gc-drmt doormat items. Each matched element
 * produces a single-row Cards block. Adjacent blocks of the same type are
 * merged during the import/transform phase.
 */
export default function parse(element, { document }) {
  const cells = [];

  // Create a single container for this card's content (1-column layout)
  const cellContainer = document.createElement('div');

  // Extract heading: h3 > a (source uses h3.h5 with anchor inside)
  // Include fallbacks for h2, h4 heading level variations
  const heading = element.querySelector('h3, h2, h4');
  if (heading) {
    cellContainer.appendChild(heading);
  }

  // Extract description paragraph
  const description = element.querySelector('p');
  if (description) {
    cellContainer.appendChild(description);
  }

  // Only create block if there is content. Row is [singleCell] for 1-column layout.
  if (cellContainer.childNodes.length > 0) {
    cells.push([cellContainer]);
  }

  const block = WebImporter.Blocks.createBlock(document, { name: 'cards-doormat', cells });
  element.replaceWith(block);
}
